package data.pipeline.components.project;

import data.pipeline.api.components.AbstractComponent;
import data.pipeline.api.error.FlowException;

public class ProjectComponent extends AbstractComponent {

    private static Class[] inputClasses={String.class};
    private static Class[] outputClasses={String.class};
    public Class[] getInputClasses() {return inputClasses;}
    public Class[] getOutputClasses() {return outputClasses;}

    public String getName() {return "Project Component";}


    @Override
    protected void executeComponent() throws FlowException {
        System.out.println("Project Component");
        System.out.println("input:"+this.getInputValue(0));
        System.out.println(this.getEnvironmentKey());
        System.out.println(this.getNodeConfiguration());
        this.setOutputValue(0,"generated by project component");
        // DO SOMETHING
        System.out.println("input:"+this.getTotalInputPorts());
        System.out.println("output:"+this.getTotalOutputPorts());
        this.setOutputValue(0,getProjectValue());
        System.out.println("output:"+this.getOutputValue(0));
    }

    private String getProjectValue() {
        return "project - " + (String) this.getInputValue(0);
    }


}
